spring.application.name=backend

server.port=8080

spring.mongodb.uri=${MONGO_URI}

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# Multipart / File Upload Size Limits
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB